Console.WriteLine("u m");
Console.WriteLine("m o v i");
Console.WriteLine("mento");
Console.WriteLine("compondo");
Console.WriteLine("além");
Console.WriteLine("         da");
Console.WriteLine("nuvem");
Console.WriteLine("  um");
Console.WriteLine(" campo");
Console.WriteLine("     de");
Console.WriteLine("combate");
Console.WriteLine();
Console.WriteLine(" mira");
Console.WriteLine("gem");
Console.WriteLine("  ira");
Console.WriteLine("         de");
Console.WriteLine(" um");
Console.WriteLine(" horizonte");
Console.WriteLine("puro");
Console.WriteLine(" num");
Console.WriteLine("vivo");
Console.WriteLine("     mo");
Console.WriteLine("     mento");
Console.WriteLine("vivo");
Console.WriteLine("Décio Pignatari — 1956");